[[Perl]]
arch = "aarch64"
git-tree-sha1 = "8257426b8a82bd4579001e45f2fce5df066275a1"
os = "macos"

    [[Perl.download]]
    sha256 = "23f7d994e524fd73cf6079092e951290fdc3bb7daa38eb66baa9c9ce765ae2a9"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.aarch64-apple-darwin.tar.gz"
[[Perl]]
arch = "aarch64"
git-tree-sha1 = "57728c4ebfea8bae72654dd593676263938b879a"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "4782f9d94c03e42b452051b8c877bf38a8f13635d96745eab72c38e452c0e3c3"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.aarch64-linux-gnu.tar.gz"
[[Perl]]
arch = "aarch64"
git-tree-sha1 = "118030a16960131713b836d1b9aa5289df7e0b95"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "0a0c5c7b92af182789e3b8baa19b6aedb082de8d288108f3a4982b2b26f0b087"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.aarch64-linux-musl.tar.gz"
[[Perl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1329d1ec0dd26a45c8fb1fea14d20c78b7c0bbcd"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "ae5b296024cbcdb6366a40453d828ef150f5c2eab979511d11bb08acbd884ff0"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.armv7l-linux-gnueabihf.tar.gz"
[[Perl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6b880a51abb19304b97ca2e6efaaa851215b4648"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "c444c85711091424088abc2f9226d7c93adeb10d1bcf3088f1809dcaddcd3f81"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.armv7l-linux-musleabihf.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "dd5bc8b66a00f5b38b4fa95a5e492a1177b96e20"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "6d92c5cf91e5f1b97129b5fa65aceb8abfd2855f45acd91a42db5cd6deae607e"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.i686-linux-gnu.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "815953d4a26ebf269cb1811e2ffd05dc32c31a3d"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "0b879758dc0eee5c35afa00838771f99bd6054390c9c7bb36286d104051c55c4"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.i686-linux-musl.tar.gz"
[[Perl]]
arch = "powerpc64le"
git-tree-sha1 = "d6cb13993b2f773427dfa26252070a529d437f44"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "3e141103eaa22f8dcf0046b884d54278edcaf31ecd56f8ef9d0b261fb86e77a2"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.powerpc64le-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "24bb99ab74ebd28b9372e15bfd701835dff50074"
os = "macos"

    [[Perl.download]]
    sha256 = "3633fbed912db087b7acfbd0bd6c74c3d75911daa73a8e3eddb8115593f36ace"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.x86_64-apple-darwin.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "c40381d447012fe8feaf450aff0fa06b1b3a1cbf"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "ee73aa9b08c393a1fe241088bcd86b1423cf1e3b883b7cd6e6337841be4abc5d"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.x86_64-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "341d1932fca1c5053e16e8ec9263553b4e272517"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "747c0d0d9109a51977895263d18f213528b1fa7e14150ad76c5ec577638848f0"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.x86_64-linux-musl.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "b5b9da43c103fcb8084339645d37e4e7e79e96bc"
os = "freebsd"

    [[Perl.download]]
    sha256 = "524a98ebbc8886ad7f0995839431692c5694ea49cf1e7a0096ed45036126f5e4"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.x86_64-unknown-freebsd.tar.gz"
