[[Perl]]
arch = "aarch64"
git-tree-sha1 = "2c277d175fb5a0613f5b272e6aec9202f39dfdac"
os = "macos"

    [[Perl.download]]
    sha256 = "92e5b3e08455c00ab7d4a381ba97344cceb8a253ed5a2ba99b9ded5fec8c3bb6"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+0/Perl.v5.34.0.aarch64-apple-darwin.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "2543ef28acd0500aa9dfcc0231d5c5d0ddfb8e56"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "55d05cdc7ea264d55f2918d456d0d28a248a4a94b31017dd656d32f8ce86af22"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+0/Perl.v5.34.0.i686-linux-gnu.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "fbbe8e19bf4c3b685c5d628f55a4e261fb9d9584"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "79ce4952b27a6951d1f5770d7fd1f08d14786fa7ad6cd0830f1d70b02782e87c"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+0/Perl.v5.34.0.i686-linux-musl.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "0688bb9c0aa7d9128026562bdf219cd31123f773"
os = "macos"

    [[Perl.download]]
    sha256 = "dfc8db320b5187aefdf2d00c4e389a778cee39431eb300e4a0870bdf99ba095e"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+0/Perl.v5.34.0.x86_64-apple-darwin.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "12b69ceec884c7bdee5cd0359136d373500c04a0"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "5c5c55f680563f1f3d40bc124b9284e5891f479711ec0334120883298c532d13"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+0/Perl.v5.34.0.x86_64-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "4f88fe9e95b7efa84796cfe5b1db4b0d2a4cdc01"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "1a82717df81ad65f9ad8dba5e7dbedd30c349225211297dbe322e5cf8a46bc5e"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+0/Perl.v5.34.0.x86_64-linux-musl.tar.gz"
