[[Perl]]
arch = "aarch64"
git-tree-sha1 = "d3cc8f268048a2d18c7cee8ca511b62a6fa8e708"
os = "macos"

    [[Perl.download]]
    sha256 = "b869c8f468adc753ac6012e65d06bf0359d718e1a4083cf95cc3cfa816563e3e"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.aarch64-apple-darwin.tar.gz"
[[Perl]]
arch = "aarch64"
git-tree-sha1 = "55d84eed465d6ec8182cb1ca5bf8ea991556e3ef"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "34b3051771f16335b11f3fa06c895f192edd16d2f3eda6503da9af79ce404855"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.aarch64-linux-gnu.tar.gz"
[[Perl]]
arch = "aarch64"
git-tree-sha1 = "579586ce0a643f03b567cabde9dd0787ba7e979d"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "67bf7552aaae4fd0a75073e938b417dfc49214c4ee218f9b5bac17d63a372feb"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.aarch64-linux-musl.tar.gz"
[[Perl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f01cb54b0431961ec56c83708e5626d388d6290"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "51b360360e80e3553c91e234919a268d58ee5c86bd82de8ca9acc5902288809d"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.armv7l-linux-gnueabihf.tar.gz"
[[Perl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "86e061226e64235af09682bf5b2538c554d0c2cf"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "ffe31b71a11de704631e695647a14093f34c11b029d31d6eebdf748dde2043dd"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.armv7l-linux-musleabihf.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "89b0b671a83a8961326440e80ccfd2594817abcb"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "499f196c06d036f31b3bebbc0c900c554f35004339a777190fe575a7985fa7f2"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.i686-linux-gnu.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "d0fe9814b7378c0b599e7b2e189f30381c4b40da"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "900818c8420fbb9ce50fddefe6105d534fda8ea60e58c00f27b27e3004c2d8e6"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.i686-linux-musl.tar.gz"
[[Perl]]
arch = "powerpc64le"
git-tree-sha1 = "0bdead36e68237519eacc01d0eee8cf1c5886b88"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "3f4aab032d0fc05ce891510f470008cc12a38f5dfc4ec51f3c81fd1df7f9a449"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.powerpc64le-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "628df679bbca6f7d1639df1e80a2e8e69648af71"
os = "macos"

    [[Perl.download]]
    sha256 = "59224d89ca17ddab8b5a2c28996c2122d881ead89f24fb4301cd6d0972382eef"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.x86_64-apple-darwin.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "a6da248842c40fe48c10ecd2b48430bf738e7ebf"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "13647b3a18eb0c308d11b26f20ef021b3071b5f71b19d32065c90029659f5620"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.x86_64-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "4de2ac1b51c0120b88a19b986b8bfd8024bce120"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "8fb469b28d40e3b0c471d634f69e3ca041bfa1d0e022186596ef820cc97a009b"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.x86_64-linux-musl.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "a42497074e484472636ea44890ce0418ce01ce32"
os = "freebsd"

    [[Perl.download]]
    sha256 = "11c4e46147a88cc45dd0ac93ce684c118343994c19f6b3d087126609d940881b"
    url = "https://github.com/benlorenz/Perl_jll.jl/releases/download/Perl-v5.34.0+1/Perl.v5.34.0.x86_64-unknown-freebsd.tar.gz"
